In [1]:
import numpy as np
import pandas as pd

In [19]:
df = pd.read_csv('BostonHousing.csv')
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [6]:
# df.drop(columns=['Unnamed: 15','Unnamed: 16'],inplace=True)

In [20]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [22]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [23]:
df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [10]:
# filling null values, if required
# for i in df.columns:
#     mean_value = df[i].mean()
#     df[i].fillna(mean_value, inplace=True)

In [14]:
df.corr()['medv'].sort_values()

lstat     -0.737663
ptratio   -0.507787
indus     -0.483725
tax       -0.468536
nox       -0.427321
crim      -0.388305
rad       -0.381626
age       -0.376955
chas       0.175260
dis        0.249929
b          0.333461
zn         0.360445
rm         0.695360
medv       1.000000
Name: medv, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split

X = df.loc[:, df.columns != 'medv']
y = df.loc[:, df.columns == 'medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

In [35]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
mms.fit(X_train)
X_train = mms.transform(X_train)
X_test = mms.transform(X_test)

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(128, input_shape=(13, ), activation='relu', name='dense_1'))
model.add(Dense(64, activation='relu', name='dense_2'))
model.add(Dense(1, activation='linear', name='dense_output'))

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 128)               1792

 dense_2 (Dense)             (None, 64)                8256

 dense_output (Dense)        (None, 1)                 65

=================================================================
Total params: 10113 (39.50 KB)
Trainable params: 10113 (39.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [37]:
history = model.fit(X_train, y_train, epochs=100, validation_split=0.05, verbose = 1)

Epoch 1/100
11/11 [==============================] - 1s 14ms/step - loss: 575.2856 - mae: 22.1253 - val_loss: 587.1887 - val_mae: 22.2728
Epoch 2/100
11/11 [==============================] - 0s 3ms/step - loss: 521.2474 - mae: 20.8357 - val_loss: 521.6231 - val_mae: 20.7045
Epoch 3/100
11/11 [==============================] - 0s 3ms/step - loss: 445.2623 - mae: 18.7946 - val_loss: 425.1630 - val_mae: 18.1296
Epoch 4/100
11/11 [==============================] - 0s 3ms/step - loss: 340.7001 - mae: 15.6786 - val_loss: 301.7892 - val_mae: 14.2716
Epoch 5/100
11/11 [==============================] - 0s 3ms/step - loss: 227.6302 - mae: 12.0950 - val_loss: 187.1031 - val_mae: 10.0138
Epoch 6/100
11/11 [==============================] - 0s 3ms/step - loss: 149.8151 - mae: 9.5239 - val_loss: 132.0985 - val_mae: 8.2266
Epoch 7/100
11/11 [==============================] - 0s 3ms/step - loss: 127.7639 - mae: 8.7540 - val_loss: 117.3583 - val_mae: 7.8557
Epoch 8/100
11/11 [==============================] - 0s 3ms/step - loss: 113.6515 - mae: 8.1842 - val_loss: 107.3387 - val_mae: 7.4130
Epoch 9/100
11/11 [==============================] - 0s 3ms/step - loss: 97.9232 - mae: 7.4367 - val_loss: 100.3292 - val_mae: 7.0002
Epoch 10/100
11/11 [==============================] - 0s 3ms/step - loss: 85.6586 - mae: 6.7722 - val_loss: 92.1304 - val_mae: 6.6151
Epoch 11/100
11/11 [==============================] - 0s 3ms/step - loss: 75.4432 - mae: 6.2963 - val_loss: 83.6964 - val_mae: 6.3357
Epoch 12/100
11/11 [==============================] - 0s 3ms/step - loss: 67.2136 - mae: 5.9448 - val_loss: 77.6734 - val_mae: 6.1275
Epoch 13/100
11/11 [==============================] - 0s 3ms/step - loss: 61.3698 - mae: 5.6640 - val_loss: 73.6038 - val_mae: 6.0353
Epoch 14/100
11/11 [==============================] - 0s 3ms/step - loss: 56.5509 - mae: 5.3465 - val_loss: 71.1966 - val_mae: 5.9053
Epoch 15/100
11/11 [==============================] - 0s 3ms/step - loss: 53.3520 - mae: 5.0647 - val_loss: 69.8636 - val_mae: 5.7426
Epoch 16/100
11/11 [==============================] - 0s 3ms/step - loss: 50.6935 - mae: 4.9422 - val_loss: 66.7998 - val_mae: 5.8545
Epoch 17/100
11/11 [==============================] - 0s 3ms/step - loss: 48.3712 - mae: 4.8647 - val_loss: 65.0717 - val_mae: 5.7375
Epoch 18/100
11/11 [==============================] - 0s 3ms/step - loss: 46.2194 - mae: 4.7273 - val_loss: 62.9995 - val_mae: 5.7099
Epoch 19/100
11/11 [==============================] - 0s 3ms/step - loss: 44.1560 - mae: 4.6085 - val_loss: 61.7063 - val_mae: 5.5727
Epoch 20/100
11/11 [==============================] - 0s 3ms/step - loss: 42.4720 - mae: 4.4715 - val_loss: 59.6585 - val_mae: 5.5301
Epoch 21/100
11/11 [==============================] - 0s 3ms/step - loss: 40.7387 - mae: 4.4941 - val_loss: 57.4542 - val_mae: 5.5159
Epoch 22/100
11/11 [==============================] - 0s 3ms/step - loss: 38.8339 - mae: 4.2838 - val_loss: 57.4689 - val_mae: 5.1899
Epoch 23/100
11/11 [==============================] - 0s 3ms/step - loss: 37.2515 - mae: 4.2504 - val_loss: 53.9388 - val_mae: 5.3485
Epoch 24/100
11/11 [==============================] - 0s 3ms/step - loss: 35.1207 - mae: 4.1104 - val_loss: 53.6136 - val_mae: 5.0710
Epoch 25/100
11/11 [==============================] - 0s 4ms/step - loss: 33.3882 - mae: 3.9636 - val_loss: 51.8922 - val_mae: 5.0101
Epoch 26/100
11/11 [==============================] - 0s 3ms/step - loss: 31.8219 - mae: 3.8795 - val_loss: 50.2500 - val_mae: 4.9717
Epoch 27/100
11/11 [==============================] - 0s 3ms/step - loss: 30.1792 - mae: 3.7809 - val_loss: 48.4551 - val_mae: 4.9574
Epoch 28/100
11/11 [==============================] - 0s 3ms/step - loss: 28.6265 - mae: 3.6957 - val_loss: 46.7842 - val_mae: 4.9490
Epoch 29/100
11/11 [==============================] - 0s 3ms/step - loss: 27.2685 - mae: 3.6227 - val_loss: 46.0956 - val_mae: 4.9154
Epoch 30/100
11/11 [==============================] - 0s 4ms/step - loss: 25.9859 - mae: 3.4925 - val_loss: 45.8158 - val_mae: 4.8780
Epoch 31/100
11/11 [==============================] - 0s 3ms/step - loss: 24.8494 - mae: 3.3684 - val_loss: 43.5512 - val_mae: 4.8374
Epoch 32/100
11/11 [==============================] - 0s 3ms/step - loss: 23.8212 - mae: 3.3998 - val_loss: 41.5675 - val_mae: 4.8099
Epoch 33/100
11/11 [==============================] - 0s 3ms/step - loss: 22.9937 - mae: 3.2492 - val_loss: 42.3303 - val_mae: 4.7097
Epoch 34/100
11/11 [==============================] - 0s 3ms/step - loss: 22.1586 - mae: 3.2631 - val_loss: 40.4026 - val_mae: 4.6912
Epoch 35/100
11/11 [==============================] - 0s 3ms/step - loss: 21.3903 - mae: 3.1362 - val_loss: 40.4903 - val_mae: 4.6235
Epoch 36/100
11/11 [==============================] - 0s 3ms/step - loss: 20.4465 - mae: 3.1189 - val_loss: 38.5887 - val_mae: 4.5681
Epoch 37/100
11/11 [==============================] - 0s 3ms/step - loss: 20.0382 - mae: 3.1058 - val_loss: 39.0971 - val_mae: 4.4935
Epoch 38/100
11/11 [==============================] - 0s 3ms/step - loss: 19.6395 - mae: 2.9910 - val_loss: 38.9245 - val_mae: 4.4344
Epoch 39/100
11/11 [==============================] - 0s 3ms/step - loss: 19.7196 - mae: 3.0944 - val_loss: 37.8842 - val_mae: 4.3884
Epoch 40/100
11/11 [==============================] - 0s 3ms/step - loss: 19.0971 - mae: 2.9424 - val_loss: 37.1670 - val_mae: 4.3116
Epoch 41/100
11/11 [==============================] - 0s 3ms/step - loss: 18.5387 - mae: 2.9492 - val_loss: 35.8143 - val_mae: 4.2708
Epoch 42/100
11/11 [==============================] - 0s 3ms/step - loss: 18.2722 - mae: 2.8774 - val_loss: 36.7577 - val_mae: 4.1799
Epoch 43/100
11/11 [==============================] - 0s 3ms/step - loss: 18.5115 - mae: 2.9637 - val_loss: 35.7893 - val_mae: 4.1400
Epoch 44/100
11/11 [==============================] - 0s 3ms/step - loss: 17.6863 - mae: 2.8445 - val_loss: 35.8826 - val_mae: 4.0979
Epoch 45/100
11/11 [==============================] - 0s 3ms/step - loss: 17.4074 - mae: 2.8228 - val_loss: 33.7746 - val_mae: 4.0825
Epoch 46/100
11/11 [==============================] - 0s 3ms/step - loss: 17.3296 - mae: 2.8604 - val_loss: 36.6424 - val_mae: 4.0393
Epoch 47/100
11/11 [==============================] - 0s 3ms/step - loss: 17.0323 - mae: 2.7627 - val_loss: 33.1643 - val_mae: 3.9652
Epoch 48/100
11/11 [==============================] - 0s 3ms/step - loss: 16.9235 - mae: 2.7846 - val_loss: 33.9620 - val_mae: 3.8862
Epoch 49/100
11/11 [==============================] - 0s 3ms/step - loss: 16.6651 - mae: 2.7547 - val_loss: 33.2268 - val_mae: 3.8493
Epoch 50/100
11/11 [==============================] - 0s 3ms/step - loss: 16.6625 - mae: 2.7620 - val_loss: 34.1387 - val_mae: 3.8610
Epoch 51/100
11/11 [==============================] - 0s 3ms/step - loss: 16.8184 - mae: 2.8003 - val_loss: 32.5118 - val_mae: 3.7808
Epoch 52/100
11/11 [==============================] - 0s 3ms/step - loss: 16.5800 - mae: 2.7193 - val_loss: 33.1518 - val_mae: 3.7906
Epoch 53/100
11/11 [==============================] - 0s 3ms/step - loss: 16.7031 - mae: 2.8181 - val_loss: 32.7411 - val_mae: 3.7622
Epoch 54/100
11/11 [==============================] - 0s 3ms/step - loss: 16.0261 - mae: 2.6661 - val_loss: 32.5484 - val_mae: 3.7403
Epoch 55/100
11/11 [==============================] - 0s 3ms/step - loss: 15.9526 - mae: 2.7160 - val_loss: 30.6672 - val_mae: 3.6478
Epoch 56/100
11/11 [==============================] - 0s 3ms/step - loss: 15.8173 - mae: 2.6570 - val_loss: 31.5396 - val_mae: 3.6699
Epoch 57/100
11/11 [==============================] - 0s 3ms/step - loss: 15.9119 - mae: 2.7058 - val_loss: 31.4511 - val_mae: 3.6438
Epoch 58/100
11/11 [==============================] - 0s 3ms/step - loss: 15.5205 - mae: 2.6311 - val_loss: 30.9567 - val_mae: 3.6025
Epoch 59/100
11/11 [==============================] - 0s 3ms/step - loss: 15.4471 - mae: 2.6222 - val_loss: 29.6607 - val_mae: 3.5299
Epoch 60/100
11/11 [==============================] - 0s 3ms/step - loss: 15.3674 - mae: 2.6569 - val_loss: 29.5711 - val_mae: 3.5087
Epoch 61/100
11/11 [==============================] - 0s 3ms/step - loss: 15.3657 - mae: 2.6137 - val_loss: 30.7187 - val_mae: 3.5485

Epoch 62/100
11/11 [==============================] - 0s 3ms/step - loss: 15.0171 - mae: 2.6082 - val_loss: 28.7047 - val_mae: 3.4547
Epoch 63/100
11/11 [==============================] - 0s 3ms/step - loss: 15.0200 - mae: 2.6229 - val_loss: 30.4617 - val_mae: 3.5076
Epoch 64/100
11/11 [==============================] - 0s 3ms/step - loss: 14.9200 - mae: 2.5690 - val_loss: 29.3686 - val_mae: 3.4356
Epoch 65/100
11/11 [==============================] - 0s 3ms/step - loss: 14.8848 - mae: 2.5881 - val_loss: 28.5337 - val_mae: 3.3961
Epoch 66/100
11/11 [==============================] - 0s 3ms/step - loss: 14.9042 - mae: 2.5649 - val_loss: 28.8176 - val_mae: 3.3815
Epoch 67/100
11/11 [==============================] - 0s 3ms/step - loss: 14.8195 - mae: 2.6185 - val_loss: 28.5742 - val_mae: 3.3588
Epoch 68/100
11/11 [==============================] - 0s 3ms/step - loss: 14.5987 - mae: 2.5503 - val_loss: 29.1670 - val_mae: 3.3587
Epoch 69/100
11/11 [==============================] - 0s 3ms/step - loss: 14.6388 - mae: 2.5278 - val_loss: 27.5250 - val_mae: 3.2972
Epoch 70/100
11/11 [==============================] - 0s 3ms/step - loss: 14.6397 - mae: 2.6222 - val_loss: 28.1033 - val_mae: 3.3096
Epoch 71/100
11/11 [==============================] - 0s 3ms/step - loss: 14.3762 - mae: 2.5192 - val_loss: 28.4036 - val_mae: 3.3059
Epoch 72/100
11/11 [==============================] - 0s 3ms/step - loss: 14.4817 - mae: 2.5732 - val_loss: 27.8426 - val_mae: 3.2789
Epoch 73/100
11/11 [==============================] - 0s 3ms/step - loss: 14.2599 - mae: 2.5092 - val_loss: 28.0854 - val_mae: 3.2754
Epoch 74/100
11/11 [==============================] - 0s 3ms/step - loss: 14.0932 - mae: 2.5232 - val_loss: 26.7264 - val_mae: 3.2244
Epoch 75/100
11/11 [==============================] - 0s 3ms/step - loss: 14.2000 - mae: 2.5006 - val_loss: 26.4099 - val_mae: 3.1953
Epoch 76/100
11/11 [==============================] - 0s 3ms/step - loss: 13.9516 - mae: 2.4987 - val_loss: 27.3601 - val_mae: 3.2163
Epoch 77/100
11/11 [==============================] - 0s 3ms/step - loss: 14.0192 - mae: 2.4585 - val_loss: 26.5371 - val_mae: 3.1661
Epoch 78/100
11/11 [==============================] - 0s 3ms/step - loss: 14.2680 - mae: 2.5879 - val_loss: 26.5661 - val_mae: 3.1628
Epoch 79/100
11/11 [==============================] - 0s 3ms/step - loss: 13.9342 - mae: 2.4764 - val_loss: 25.8334 - val_mae: 3.1186
Epoch 80/100
11/11 [==============================] - 0s 3ms/step - loss: 13.7698 - mae: 2.4812 - val_loss: 26.4813 - val_mae: 3.1538
Epoch 81/100
11/11 [==============================] - 0s 3ms/step - loss: 13.5655 - mae: 2.4718 - val_loss: 24.7817 - val_mae: 3.0914
Epoch 82/100
11/11 [==============================] - 0s 3ms/step - loss: 13.6486 - mae: 2.4439 - val_loss: 25.8183 - val_mae: 3.1290
Epoch 83/100
11/11 [==============================] - 0s 3ms/step - loss: 13.4431 - mae: 2.4666 - val_loss: 25.0508 - val_mae: 3.0635
Epoch 84/100
11/11 [==============================] - 0s 3ms/step - loss: 13.3704 - mae: 2.4330 - val_loss: 25.1214 - val_mae: 3.0794
Epoch 85/100
11/11 [==============================] - 0s 3ms/step - loss: 13.3667 - mae: 2.4758 - val_loss: 26.0866 - val_mae: 3.1071
Epoch 86/100
11/11 [==============================] - 0s 3ms/step - loss: 13.2554 - mae: 2.3994 - val_loss: 24.0978 - val_mae: 2.9958
Epoch 87/100
11/11 [==============================] - 0s 3ms/step - loss: 13.4463 - mae: 2.4926 - val_loss: 24.6852 - val_mae: 3.0356
Epoch 88/100
11/11 [==============================] - 0s 3ms/step - loss: 13.2083 - mae: 2.4093 - val_loss: 24.7728 - val_mae: 3.0236
Epoch 89/100
11/11 [==============================] - 0s 3ms/step - loss: 13.0632 - mae: 2.4647 - val_loss: 24.0530 - val_mae: 2.9997
Epoch 90/100
11/11 [==============================] - 0s 3ms/step - loss: 12.9764 - mae: 2.3818 - val_loss: 24.1625 - val_mae: 2.9872
Epoch 91/100
11/11 [==============================] - 0s 3ms/step - loss: 12.7665 - mae: 2.3988 - val_loss: 22.9630 - val_mae: 2.8986
Epoch 92/100
11/11 [==============================] - 0s 3ms/step - loss: 12.7585 - mae: 2.3996 - val_loss: 23.7481 - val_mae: 2.9162
Epoch 93/100
11/11 [==============================] - 0s 3ms/step - loss: 12.7474 - mae: 2.3932 - val_loss: 23.2055 - val_mae: 2.8860
Epoch 94/100
11/11 [==============================] - 0s 3ms/step - loss: 12.6952 - mae: 2.3744 - val_loss: 23.8013 - val_mae: 2.8718
Epoch 95/100
11/11 [==============================] - 0s 3ms/step - loss: 12.6280 - mae: 2.3595 - val_loss: 22.3101 - val_mae: 2.8178
Epoch 96/100
11/11 [==============================] - 0s 3ms/step - loss: 12.5518 - mae: 2.3760 - val_loss: 23.5705 - val_mae: 2.9110
Epoch 97/100
11/11 [==============================] - 0s 3ms/step - loss: 12.4327 - mae: 2.3628 - val_loss: 22.5009 - val_mae: 2.8139
Epoch 98/100
11/11 [==============================] - 0s 3ms/step - loss: 12.3663 - mae: 2.3380 - val_loss: 22.5494 - val_mae: 2.8169
Epoch 99/100
11/11 [==============================] - 0s 3ms/step - loss: 12.3289 - mae: 2.3600 - val_loss: 22.0917 - val_mae: 2.7842
Epoch 100/100
11/11 [==============================] - 0s 3ms/step - loss: 12.3113 - mae: 2.3517 - val_loss: 21.2772 - val_mae: 2.7398

In [38]:
mse_nn, mae_nn = model.evaluate(X_test, y_test)

print('Mean squared error on test data: ', mse_nn)
print('Mean absolute error on test data: ', mae_nn)

5/5 [==============================] - 0s 1ms/step - loss: 21.3914 - mae: 3.0060
Mean squared error on test data:  21.391441345214844
Mean absolute error on test data:  3.0059902667999268

In [39]:
y1 = model.predict(X_test[:])

5/5 [==============================] - 0s 1ms/step

In [45]:
ps=[]
for i in y1:
    ps.append(list(i)[0])

In [46]:
d = pd.DataFrame({'actual':y_test['medv'],'predicted':ps})

In [40]:
y_test.head()

     medv
410  15.0
85   26.6
280  45.4
422  20.8
199  34.9

In [49]:
d.head(10)

     actual  predicted
410    15.0  13.803579
85     26.6  26.968628
280    45.4  43.755100
422    20.8  16.464979
199    34.9  28.809629
364    21.9  44.586136
5      28.7  25.560226
415     7.2  11.657738
209    20.0  15.122553
284    32.2  29.776974